### ISSUE TITLE
Extremely slow or crashing WP Dashboard w' action logs in wp_comment table

### ISSUE THREAD

**Issue by james-allan** [woocommerce/action-scheduler#368] opened 2019-10-08 02:15 UTC
Reported initially by @thenbrent, if your site has lots of `action-scheduler` comments left in the `wp_comments` table after the migration is completed, the WP admin dashboard screen takes a long time to load or just crashes with memory exhaustion errors. 

This morning I was able to replicate this on my local. 

On my daily dev site, I have ~120K comments with the `comment_agent` as `ActionScheduler`. This causes the dashboard to crash because WP tries to generate the comment count as part of the **_At a glance_** or **_Activity_** widget.

### Why are there ~120K AS comments left after migration?

There are a few theories but I think there's a high possibility that they came from the WC webhook issue or an issue early in AS 3.0 dev that caused an infinite loop and scheduled actions basically duplicating themselves. After those issues corrupted your database you'd typically just delete all scheduled actions and call it a day. 

Because I deleted the posts manually via query, the comments associated with them remained. 

### Why is it crashing?
Having these comments causes the widget to crash because after migration is completed, the `ActionScheduler_Logger` instance [is switched over to to the `ActionScheduler_DBLogger`](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_DataController.php#L155-L157) class, the `ActionScheduler_wpCommentLogger` is no longer loaded and [so none of the functions which filter out the AS comments](https://github.com/Prospress/action-scheduler/blob/87d0429/classes/data-stores/ActionScheduler_wpCommentLogger.php) are hooked in.

### Possible fixes

To fix this issue we can:

1. We can continue to load the `ActionScheduler_wpCommentLogger` and the hooked functions which filter out AS comments. 
2. Delete all the scheduled comments after the migration is complete to ensure there aren't any left. This is destroying data so not a great idea in case there's an issue with the migration or in case we want to keep the data for troubleshooting.
3. Other ideas?

**Comment by james-allan** [comment] 2019-10-08 02:33
> I think there's a high possibility that they came from the WC webhook issue or an issue early in AS 3.0 dev... [and] because I deleted the posts manually via query

The reason behind this theory is that I have these comments by action scheduler grouped by date. 

<img width="188" alt="Screen Shot 2019-10-08 at 12 30 13 pm" src="https://user-images.githubusercontent.com/8490476/66362820-7e67b400-e9c7-11e9-97aa-d83adf264619.png">

I had 119,767 total comments created in the space of 2 days.

**Comment by thenbrent** [comment] 2019-10-08 02:49
> 3. Other ideas?

We could also:

1. add new code to include the `ActionScheduler_wpCommentLogger` methods related to filtering comments, but avoid loading`ActionScheduler_Logger` and unrelated methods (it would be confusing to have two log data stores loaded / initialised)
2. set a scheduled action to delete all orphaned comments at some point in the future, like 6 months from updating to 3.0.0, which allows time to review the data if there are problems caused by it
3. check on the Scheduled Actions admin screen if there are any orphaned comments, and if so, link to this Issue or some other doc with background on the issue and instructions for fixing it manually (i.e. delete orphaned comments) if sure that data isn't orphaned by something else, like an error with migration.

**Comment by james-allan** [comment] 2019-10-09 03:58
I've started to look into how to do this and struggling to find the right place to put this new code. I just don't have the high-level view of the migration stuff to know what each class is responsible for and which classes are abstract - shouldn't have knowledge of comment table count etc. 

I'm going to give it a crack and submit a PR but I'm suspecting it will look gross to those with a better understanding of where things live 😆

**Comment by thenbrent** [comment] 2019-10-09 05:31
> struggling to find the right place to put this new code

There's no existing class that would be a good fit. It can live in a new, separate class that is only loaded when the active logging data store `!== ActionScheduler_wpCommentLogger`.

> I'm going to give it a crack

:100:

**Comment by thenbrent** [comment] 2019-10-16 02:58
Fixed with #369.

**Closed by thenbrent** 2019-10-16 02:58 UTC
Labels: bug, hasPR

**Comment by crstauf** [comment] 2020-06-02 13:48
For those ending up here from their WordPress Dashboard wondering what the hook name is, it is (currently) `action_scheduler/cleanup_wp_comment_logs`.

**Comment by abhishek-pokhriyal** [comment] 2020-06-29 07:20
@crstauf So, I can run the following command to clear the comments?

```
wp action-scheduler run --hooks=action_scheduler/cleanup_wp_comment_logs
```

**Comment by oempire** [comment] 2020-07-27 04:28
> @crstauf So, I can run the following command to clear the comments?
> 
> ```
> wp action-scheduler run --hooks=action_scheduler/cleanup_wp_comment_logs
> ```

id like to know this aswell
