### ISSUE TITLE
Warn the user whenever they have past-due actions

### ISSUE THREAD

**Issue by crodas** [woocommerce/action-scheduler#91] opened 2017-08-25 22:17 UTC
While I was doing support I had this idea. I believe it is fairly easy for Action-Scheduler to warn the user whenever they have past-due actions. It can even wait for a threshold (like a day or two).

It be built on top of the [admin notices API](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices) and have some link to our documentation which explains what may be wrong and how to fix it. 

It should also give the option to run the past-due actions manually. Although these things are possible (detect there are past-due actions, and run actions manually) I believe it is worth to make them obvious and super simple to diagnose problems, offer a temporarily (run the actions now) and a permanent solution (run the crons)

**Comment by thenbrent** [comment] 2017-08-25 22:33
I think this would be good to include in Action Scheduler. We should make the notice filterable though.

That would allow us to do things like link to the _Submit a Ticket_ form when Subscriptions is active and using Action Scheduler (we can't do that in the generic AS message, because it should have no knowledge of what's using it).

**Comment by crodas** [comment] 2017-08-25 22:47
> I think this would be good to include in Action Scheduler. We should make the notice filterable though.

Yes, it should a built-in in the library itself and Subscriptions should be able to filter it. I like that idea.

**Comment by crodas** [comment] 2017-09-07 23:15
We can also run a few checks to warn the user. We can check that:

  1. Our tasks are running
  2. That WP-Cron is enabled
  3. If our site is not behind cloudflare or a CDN/accelerator that may interrupt the cron calls
  4. If curl against _localhost_ (I think WooCommerce does not do that).

**Comment by thenbrent** [comment] 2018-03-12 22:37
#106 contains a WIP for this, but I've closed it because the base branch (`issue_85`) and PR (#88) were overridden in parts by the patches in #113. Once #113 is merged, I'll `cherry-pick` the relevant patches from #106 onto a new branch and submit a PR.

**Comment by crstauf** [comment] 2019-02-26 22:19
Ran into this today. We noticed that subscription renewals were not being processed, so I started digging. Turns out we had 73k+ scheduled actions pending (passed their scheduled date)! Not sure what the cause was yet, but definitely would've helped to have known that sooner rather than today.

**Comment by thenbrent** [comment] 2019-02-27 02:52
@crstauf the cause will almost certainly be this: https://github.com/woocommerce/woocommerce/issues/22087

That's been fixed with https://github.com/woocommerce/woocommerce/pull/22088

Please update WooCommerce to make sure duplicates aren't being scheduled still. If you need help clearing the queue of existing actions, please submit a support ticket to Prospress here: https://prospress.com/support/ :)

**Comment by crstauf** [comment] 2019-02-27 03:17
Thanks, @thenbrent. I've already a ticket open... is there something specific I should say?

**Comment by thenbrent** [comment] 2019-02-27 03:56
Thanks @crstauf I found the ticket and have replied. :)

**Comment by crstauf** [comment] 2019-02-28 23:05
I think two qualifications for displaying the notice would suit most uses, both filterable:
- number of seconds old
- total number of past due actions

The two thresholds should be inclusive or exclusive, combinable or independent... `&&` or `||`.

There should also be a master filter, so that devs can specify whether and/or to whom the notice shows.

**Comment by crstauf** [comment] 2020-03-31 18:30
> Once #113 is merged, I'll `cherry-pick` the relevant patches from #106 onto a new branch and submit a PR.

@thenbrent #113 was merged in 2018, but it doesn't appear there's a PR for this. I'm willing to work on a PR for this, but don't want to interfere with or duplicate what you're doing (or going to do).

**Comment by thenbrent** [comment] 2020-04-01 01:41
@crstauf thanks! There's no recent work on this, though the functionality would still be quite valuable. @rrennick would you review / merge a PR for this?

**Comment by rrennick** [comment] 2020-04-01 13:52
@crstauf What I have in mind for this month is to create a 3.2.0 branch after 3.1.5 is tagged & released. Once we have that branch PRs for 3.2 can be based to that branch without affecting our ability to do a 3.1.6 bugfix release if necessary.

**Comment by SevenAcreFarm** [comment] 2020-11-12 15:50
We would like to support this enhancement. 

We have experienced an issue wherein pending actions are scheduled, but blocked from running by a stuck process. Since the system seems to be designed such that only one action can be ran at a time, any issues causing a stuck action holds up /every other action/ thereafter. This seems like a major bug.

To add insult to injury, there are no warnings, emails, or alerts generated to let the admin know there is a critical failure within the system. None of our subscription renewals were processing, no renewal emails were sent, no charges were made... but the "renew" date kept getting updated each day, and all subscriptions remained "Active." We discovered the issue when there was a lack of renewal emails and our revenue dropped to zero. Renewals had not been processed in over a week.

Turns out that the stuck process was related to a Woo update, and was the wcs_report_update_cache hook that caused the holdup. We also had the error "Action Scheduler migration in progress. The list of scheduled actions may be incomplete," but that was only noticed once this issue became critical and we started working with support to understand what was happening.

We would like to support this enhancement to generate alerts when there is a critical failure within the system, so that our team can be alerted as soon as possible in order to minimize fallout and address the issue quickly. Without these alerts our team remains unaware of critical issues until their magnitude reaches a point of requiring investigation, and the fallout from which is then magnified due to the delay.

We would also be in support of, if possible, increasing the max threads so that a single stuck process does not prevent the system from performing other, possibly unrelated, actions. A single hung process should be alerted upon and addressed, and should not bring the entire system crashing to a halt.

We currently do not utilize WP Cron either, and are running our cron jobs directly via the server. Thus this enhancement should also address those types of installations wherein WP Cron my not be specifically in use. We are also behind Cloudflare, but I fail to understand how that may impact these internally scheduled processes.

We are utilizing WP 5.5.3, WC 4.7.0, and WC Subscriptions 3.0.10 running on an AWS LEMP stack.



![Screen Shot 2020-11-12 at 10 25 48 AM](https://user-images.githubusercontent.com/63859031/98961275-6409df00-24d3-11eb-9ff8-68da01623e9f.png)
![Screen Shot 2020-11-12 at 10 27 03 AM](https://user-images.githubusercontent.com/63859031/98961285-666c3900-24d3-11eb-9981-d521335f9d3e.png)

**Closed** 2022-08-03 07:58 UTC
Labels: type: enhancement
