### ISSUE TITLE
Duplication of repetitive actions

### ISSUE THREAD

**Issue by ComradeWebAgency** [woocommerce/action-scheduler#797] opened 2022-01-31 06:34 UTC
Hello. I created a repeating as_schedule_cron_action and at the time of execution it is duplicated many times, but if run through the admin panel, it is not duplicated.

add_action('init', array($this, 'slabs_sync_cron'));

public function slabs_sync_cron() {
if ( false === as_next_scheduled_action( ‘sync_slabsmith_products_cron’ ) ) {
as_schedule_cron_action( time(), ‘* */10 * * * *’, ‘sync_slabsmith_products_cron’, [], $group = ‘slabsmith_products’ );
}
if ( false === as_next_scheduled_action( ‘sync_slabsmith_products_to_wp’ ) ) {
as_schedule_cron_action( time(), ‘0 23 * * * *’, ‘sync_slabsmith_products_to_wp’, [], $group = ‘slabsmith_products’ );
}
}`
`
The worker is launched via WP-CLI. Standard plugin cron is disabled. I found an old post on this topic, but it did not help me https://github.com/woocommerce/action-scheduler/issues/387

**Comment by barryhughes** [comment] 2022-01-31 17:09
@ComradeWebAgency I cannot immediately seem to replicate: if I run (a very slightly modified version of) the above code via WP CLI, then no more than two scheduled actions are created.

In your case, how many duplicates are being created exactly? For example, each time you run this script via WP CLI, do you see precisely one more `'sync_slabsmith_products_cron'` action and one more `'sync_slabsmith_products_to_wp'` action being added—or are more than that being added?

**Comment by ComradeWebAgency** [comment] 2022-02-01 05:42
@barryhughes around 10-15 'sync_slabsmith_products_cron' is created

**Comment by barryhughes** [comment] 2022-02-01 17:14
Thanks for those screenshots, those were helpful (I wasn't initially sure what sort of duplication—or lack of—you were seeing).

> Around 10-15 'sync_slabsmith_products_cron' is created. 
>
> https://capture.dropbox.com/v3a5j0nOJgDfI4bM 
> https://capture.dropbox.com/gOoBHkosriqyChYK 
>
> Although pending has only two main jobs

So this doesn't seem unexpected (unless I'm misunderstanding the problem). 

You have created a recurring scheduled action and you have set it to repeat every minute of every tenth hour of the day (`* */10 * * *`) and so, for each hook, we would generally expect to see one pending action and, if enough time has passed, multiple completed actions—which is what your screenshots reflect.

This is because each time a recurring action is run, it is marked as 'completed' and a fresh pending action is created.

> If run through the admin panel, it is not duplicated.

Exactly the same thing should be happening (and does in my local testing). That is, if I manually run a recurring action like this one, it is marked as 'completed' and a fresh pending action is generated to replace it.

If that is not happening, that would be a problem—but it is not something I see locally.

**Comment by barryhughes** [comment] 2022-02-08 21:08
Closing as this sounds like the expected behavior, but please do comment if you believe there is still an issue to be resolved.

**Closed by barryhughes** 2022-02-08 21:08 UTC
Labels: type: support request
