### ISSUE TITLE
Wp Cron not running

### ISSUE THREAD

**Issue by Roger120200** [woocommerce/action-scheduler#644] opened 2020-12-05 21:48 UTC

**Comment by Roger120200** [comment] 2020-12-05 21:52
WP Cron |   | ✕ WP Cron does not appear to be running. This function is heavily relied upon by AutomateWoo. Please contact your hosting provider to resolve the issue.
-- | -- | --



The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

The REST API request failed due to an error.
Error: cURL error 35: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure (http_request_failed)

Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.

The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error: cURL error 35: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure (http_request_failed)

The scheduled event, action_scheduler_run_queue, failed to run. Your site still works, but this may indicate that scheduling posts or automated updates may not work as intended.

**Comment by roykho** [comment] 2021-01-12 21:32
Hi @Roger120200

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to support questions.
​
The best place to get help further is in the WooCommerce Community Slack in the #developers channel.
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed by roykho** 2021-01-12 21:32 UTC
Labels: type: support request
