### ISSUE TITLE
Action scheduler overloads server

### ISSUE THREAD

**Issue by alexanderkotev** [woocommerce/action-scheduler#700] opened 2021-05-26 13:21 UTC
I received a message from the hosting provider that my site will be shut down because of server overloading. When I investigated the issue I found that error which is logged in the errors log on the server:

`[26-May-2021 11:20:11 UTC] WordPress database error Table 'threec719_sim.wp_actionscheduler_logs' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_logs` made by do_action('wp_ajax_as_async_request_queue_runner'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Async_Request->maybe_handle, ActionScheduler_AsyncRequest_QueueRunner->handle, do_action('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, do_action('action_scheduler_execution_ignored'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_Logger->log_ignored_action, ActionScheduler_DBLogger->log`

I disabled all other plugins and narrowed the issue to the woocommerce plugin alone, probably after an automatic update that issue occured. Tried with older versions - no luck.

**Comment by barryhughes** [comment] 2021-06-04 15:56
Hi @alexanderkotev,

The error suggests that the `wp_actionscheduler_logs` table was deleted (and, if so, it's not surprising that the error log is filling with complaints about that problem). To remedy this, while logged into the admin environment, try navigating to **Tools → Scheduled Actions** ... it will hopefully detect that the log table is missing and you'll see a message like this:

![as-tools-page](https://user-images.githubusercontent.com/3594411/120829579-689af100-c512-11eb-9562-9b9a9b98e930.png)

Give it a moment, refresh, and with luck the message will be gone and the table will have been repaired.

---

> I received a message from the hosting provider that my site will be shut down because of server overloading.

I just want to be sure I'm understanding things: do you (or does your host) believe Action Scheduer is the cause of the server overloading, or did you post here because you felt that the missing table error was an indicator that Action Scheduler was responsible?

(Do you happen to know how it came to be deleted—did your host do this, and if so did they let you know why they chose to remove the table versus simpy emptying it?)

**Comment by barryhughes** [comment] 2021-06-21 20:55
It's been over a couple of weeks without an update, so I'll go ahead and close this. Reach out if you disagree/have more information as requested.

**Closed by barryhughes** 2021-06-21 20:55 UTC
Labels: needs feedback
