### ISSUE TITLE
"as_schedule_cron_action" doesn't work properly

### ISSUE THREAD

**Issue by ulver2812** [woocommerce/action-scheduler#387] opened 2019-11-05 12:10 UTC
Hi, I'm running the 2.2.5 version and I'm trying to use the "as_schedule_cron_action" but I can't understand if I found a bug or I'm using it in a wrong way. 

Here the code:

```
function register_cron_scheduler(){
    if ( false === as_next_scheduled_action( 'run_cron_action' ) ) {
        as_schedule_cron_action(time(), '00 12 * * * *', 'run_cron_action', [], 'run_cron_action_group');
    }
}
add_action('init','register_cron_scheduler');

function do_something(){
// do something
}
add_action('run_cron_action','do_something');
```

The behavior is supposed to be this: the scheduled action runs the function do_something once a day at the 12:00 and then it will be scheduled again for the next day at the same time.

![1](https://user-images.githubusercontent.com/25301598/68206576-57ec6700-ffcd-11e9-891d-2fcf396e8902.PNG)

The issue is that after the first correct execution I see in the "scheduled action" admin page more then one rescheduled action (as you can see in the image), one that is in pending with "Non-repeating" reccurrence and other two identical with the correct scheduled date.

![2](https://user-images.githubusercontent.com/25301598/68206583-5cb11b00-ffcd-11e9-834e-f9f9dab1be4a.PNG)

I would excpect to see one new scheduled action with the next recurring date, is it right?

**Comment by rrennick** [comment] 2019-11-05 15:05
@ulver2812 Are you able to check this with the AS 3.0.0 RC ?

**Comment by ulver2812** [comment] 2019-11-05 15:37
Yes, I can try, but it's secure to use a RC version in production?

**Comment by ulver2812** [comment] 2019-11-05 15:48
I just tried the 3.0.0-beta-1 but I get this error:

`Fatal error: Uncaught Error: Cannot call abstract method ActionScheduler_Logger::init()`

**I'm using also WooCommerce 3.6.4** maybe there's some conflicts with this plugin or something else.

**Comment by rrennick** [comment] 2019-11-05 16:50
> but it's secure to use a RC version in production?

I was hoping you had a dev/staging site.

> I just tried the 3.0.0-beta-1 but I get this error:

The RC contains quite a few fixes to the beta.

>Cannot call abstract method ActionScheduler_Logger::init()
> I'm using also WooCommerce 3.6.4 

We'll have to see if we can reproduce that issue.

**Comment by thenbrent** [comment] 2019-11-06 01:33
@ulver2812 cron and recurring actions were quite broken with AS < 3.0. See #330. I expect `as_schedule_cron_action()` should work as expected with 3.0, but it would still be good to confirm.

**Comment by ulver2812** [comment] 2019-11-06 09:32
@thenbrent so the only thing that work is "as_schedule_single_action", is it right ?

@rrennick yes, I have a dev/staging site but at the end I need this feature on the production site, so even if the 3.0.0 RC works correctly I can't use it until the 3.0.0 is ready for production.

My main doubt is that WooCommerce comes with a built-in action-scheduler (I guess version < 3.0.0), so if I use the 3.0.0 in my plugin the version that will be loaded globally is the 3.0.0, this version will work properly with WooCommerce ?

When will be released the 3.0.0 version production ready ?

Thanks

**Comment by rrennick** [comment] 2019-11-06 12:18
> if I use the 3.0.0 in my plugin the version that will be loaded globally is the 3.0.0, this version will work properly with WooCommerce ?

Action Scheduler is designed to use the latest version when multiple versions are registered/active. WooCommerce is alway active in my dev install so all the development work I did on the 3.0.0 version was done while WC was active.

**Comment by thenbrent** [comment] 2019-11-07 00:21
> When will be released the 3.0.0 version production ready ?

These are the open issues for 3.0: https://github.com/woocommerce/action-scheduler/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.0

At this stage, none of those will block tagging the 3.0 stable release ready for production. The reason we haven't tagged a stable release yet is primarily operational - we have a release plan that includes releasing it in WooCommerce Subscriptions, as the team working most closely with it is also most familiar with Action Scheduler. That would allow us to address issues quickly.

For your purposes, running 3.0.0-RC-3 on your live site should be fine. We keep an active eye on issues being reported here, so can help address anything you find. We may need site and/or server access if any tricky issues come in though to properly address it.

**Comment by ulver2812** [comment] 2019-11-07 10:23
Just tried the 3.0.0-RC-3 and the error:

`Fatal error: Uncaught Error: Cannot call abstract method ActionScheduler_Logger::init() in vendor\woocommerce\action-scheduler\classes\data-stores\ActionScheduler_DBLogger.php:102`

still persist 😔

**Comment by thenbrent** [comment] 2019-11-07 23:42
It looks like maybe an older version of `ActionScheduler_Logger` is being loaded somehow. `ActionScheduler_Logger::init()` was abstract until version 2.1. We have seen this error before: https://github.com/Prospress/action-scheduler-custom-tables/issues/46

Can you search the site codebase for `action_scheduler_register_2_dot_` and see what shows up? If you have any that show a version < 2.1, that could explain this.

@rrennick our autoloaded should only be loading from the initialized version shouldn't it? Is there something else we need to do, like #388, to make sure of that?

**Comment by ulver2812** [comment] 2019-11-08 08:47
> Can you search the site codebase for action_scheduler_register_2_dot_ and see what shows up? If you have any that show a version < 2.1, that could explain this.

@thenbrent yes, I found the action hook `action_scheduler_register_2_dot_2_dot_5` in WooCommerce plugin.

This is the code snippet of this hook in WooCommerce 3.6.4

```
add_action( 'plugins_loaded', 'action_scheduler_register_2_dot_2_dot_5', 0, 0 );

function action_scheduler_register_2_dot_2_dot_5() {
	$versions = ActionScheduler_Versions::instance();
	$versions->register( '2.2.5', 'action_scheduler_initialize_2_dot_2_dot_5' );
}
```

but it refers to the version 2.5.5...

**Comment by rrennick** [comment] 2019-11-08 12:18
> our autoloaded should only be loading from the initialized version shouldn't it?

Yes.

`in vendor\woocommerce\action-scheduler`

@ulver2812 Are WooCommerce & Action Scheduler being installed via WP or some other way?

**Comment by ulver2812** [comment] 2019-11-08 14:04
@rrennick WooCommerce is installed as a plugin (a normal WooCommerce installation) and the action scheduler that I'm using is a dependency of a WP plugin of mine installed through composer. 

So, in this scenario I have two WP plugin (WooCommerce 3.6.4 and my plugin) that are using two different version of action scheduler.

**Comment by rrennick** [comment] 2019-11-08 14:27
> in this scenario I have two WP plugin (WooCommerce 3.6.4 and my plugin) that are using two different version of action scheduler.

The error is occurring in the version you are installing via composer. Can you install AS directly & activate it instead of using the version embedded in your plugin?

**Comment by ulver2812** [comment] 2019-11-08 14:41
@rrennick yes, I can use it as a stand alone plugin but I need it in my plugin codebase. 
I don't like the idea that users need to install another plugin because mine is dependent by it.

In the documentation is written:

> There are two ways to install Action Scheduler:
> 1. regular WordPress plugin; or
> 2. a library within your plugin’s codebase.

I prefer the second option if it's possible.

You are suggesting to install AS as a stand alone plugin because the 3.0.0-RC-3 is not ready to work as a library or because this new version must be installed as a stand alone plugin ?

**Comment by rrennick** [comment] 2019-11-08 14:51
> You are suggesting to install AS as a stand alone plugin

Yes. We currently don't know what is triggering the error in your install. If we test it installed directly then we will find out whether it's something in AS that we missed or something in the way your composer plugin is loading it.

> I just installed AS as a stand alone plugin but I still get the same error

Thanks. In that case, this is most likely a PHP configuration issue.

**Comment by ulver2812** [comment] 2019-11-08 15:13
> Thanks. In that case, this is most likely a PHP configuration issue.

Ok, I'm using XAMPP on windows 10 as development environment, default configuration with PHP 7.2.16. 

What do you suggest in order to investigate this issue ?

What has changed from the 2.5.5 (that is loaded correctly) to the 3.0.0 that can cause this issue ?

Thanks

**Comment by rrennick** [comment] 2019-11-08 15:20
@ulver2812 I did some searching and found this issue had cropped up elsewhere in other FOSS projects so I think we should address this within AS.

@thenbrent If I don't get to a PR later today we should move the contents of `ActionScheduler_Logger::init()` to a protected `hook_all_actions()`, call that from `init()`, then in `ActionScheduler_DBLogger::init()` call `$this->hook_all_actions()`. That way we avoid referencing the function through the abstract class.

**Comment by thenbrent** [comment] 2019-11-11 01:34
> we should move the contents of `ActionScheduler_Logger::init()` to a protected `hook_all_actions()`, call that from `init()`, then in `ActionScheduler_DBLogger::init()` call `$this->hook_all_actions()`. That way we avoid referencing the function through the abstract class.

Is it the abstract class that's causing the issue, or that `ActionScheduler_Logger` from a different filepath is being loaded (i.e. the version in WC is being loaded, not the one in Composer or the standalone plugin).

If it's the latter, I'd like to figure out how to fix that. If we don't, we could end up playing whack-a-mole with any methods used in 3.0, but not available in base classes prior to 3.0.

**Comment by thenbrent** [comment] 2019-11-11 03:07
@ulver2812 do you have Follow-Up Emails installed by any chance?

We've received a report that Follow-Ups has this code in `class-fue-action-scheduler-logger.php`:

```php
/**
 * Class FUE_ActionScheduler_Logger
 *
 * Stops Action Scheduler from saving logs as WP Comments
 */
if ( ! class_exists( 'ActionScheduler_wpCommentLogger' ) ) {
    require_once 'lib/action-scheduler/classes/ActionScheduler_Logger.php';
    require_once 'lib/action-scheduler/classes/ActionScheduler_wpCommentLogger.php';
}
```

FUE is overloading Action Scheduler's autoloader.

**Comment by ulver2812** [comment] 2019-11-11 09:38
@thenbrent You got it! I have Follow-Up-Emails installed and it is the guilty of the error

`Fatal error: Uncaught Error: Cannot call abstract method ActionScheduler_Logger::init()`

Now with FUE disabled the error is gone but with this code (action scheduled to run every 5 minutes, just for test purpose):

```
function register_guacci_csv_downloader_scheduler()
  {
     if ( false === as_next_scheduled_action( 'run_guacci_csv_download_action' ) ) {
         as_schedule_cron_action(strtotime("+1 minutes"), '*/5 * * * * *', 'run_guacci_csv_download_action', [], 'guacci_csv_downloader');
      }
  }
add_action('init','register_guacci_csv_downloader_scheduler');
```
I get this scenario:

![Cattura](https://user-images.githubusercontent.com/25301598/68576641-be123780-046e-11ea-9519-1b813f5e9d69.PNG)

First event scheduled and fired correctly, next event scheduled twice, it seems that for an instant the if check return false two times and the event is scheduled twice.

**Comment by thenbrent** [comment] 2019-11-11 11:27
Thanks for confirming! At least we've figured out one of the bugs. We'll continue to investigate the other.

**Comment by ulver2812** [comment] 2019-11-11 11:38
@thenbrent thank you, if I can be helpful with some test in my environment just ask me.

**Comment by krazik** [comment] 2019-11-12 16:29
I commented on https://github.com/woocommerce/action-scheduler/issues/386

>>>I am also getting duplicate scheduled actions.  I have isolated my problem to this line of code https://github.com/woocommerce/action-scheduler/blob/52bd35581c73c77094b0b2dd4b639e595a009457/functions.php#L140

my action takes about 30 seconds to run, during that time there are no actions with `pending` status.  Just one in process and a bunch of complete, so this causes `as_next_scheduled_action` to return false then the you create a 2nd (or over time a 3rd or 4th copy). 

Seems you should also check for running process here.

**Comment by krazik** [comment] 2019-11-12 16:34
I'm running whatever version comes with woo 3.8.

**Comment by thenbrent** [comment] 2019-11-13 03:30
@krazik thanks for the report and diagnosis. I think you're right, that is most likely the culprit here. We need to figure out a way for `as_next_scheduled_action()` to account for `in-progress` actions to handle long running actions.

The ideal would be for it to return `0` when an `in-progress` action exists (i.e. the next instance is currently running so its timestamp is now).

Anyone doing loose comparison, e.g. `false == as_next_scheduled_action( 'my_hook' )` would still encounter this issue though if we go with that approach. Instead, we could return boolean `true` as a special case to say there is a scheduled action and it's running right now.

The other option is to deprecate `as_next_scheduled_action()`, and instead add two new functions:

* `as_has_scheduled_action()` - for use in cases like this, where code needs to find if there is any existing action scheduled. This would check for both `in-progress` and `pending` actions.
* `as_get_next_scheduled_action_time()` - for use when you need to find the time of the next instance of a `pending` action.

@rrennick thoughts?

**Comment by thenbrent** [comment] 2019-11-13 04:14
I just realized `as_next_scheduled_action()` is already returning `true` in 3.0+ for async actions, because they have no future date. So I will submit a PR to have it do that now for `in-progress` actions too.

**Comment by thenbrent** [comment] 2019-11-13 04:24
I've submitted a fix for this in https://github.com/woocommerce/action-scheduler/pull/392

**Comment by krazik** [comment] 2019-11-13 04:34
thanks for quick fix!  my fix was lower tech but also worked.  Basically once it starts running it creates a new single run action 30 minutes in the future.  Once your PR is merged I'll switch back

```
if (as_next_scheduled_action('something') === false) {
    as_schedule_single_action(time() + (30 * 60), 'something');
}
```

thanks!

**Comment by ulver2812** [comment] 2019-11-13 12:36
@thenbrent just tested the #392 and it doesn't fix the issue, I get the same result posted here:

https://github.com/woocommerce/action-scheduler/issues/387#issuecomment-552366380

**Comment by ulver2812** [comment] 2019-11-13 12:55
@thenbrent just tested the #392 and it fix the issue, thanks!

**Comment by thenbrent** [comment] 2019-11-14 00:55
Thanks @ulver2812!

**Closed** 2019-11-14 00:55 UTC

**Comment by aubreypwd** [comment] 2022-08-08 18:11
My issue was that I was trying to hook into `plugins_loaded`, which made `as_has_scheduled_action()` not work right, use `init`.
