### ISSUE TITLE
CRITICAL Uncaught RuntimeException: Error saving action: Unable to save action.

### ISSUE THREAD

**Issue by aseelashraf** [woocommerce/action-scheduler#611] opened 2020-09-04 23:13 UTC
im trying to access woocommerce in my Wordpress admin but I get this error
.. i tried several ways to solve this but no luck ..
PLEASE HELP ME
I tried to install action scheduler didn't work
I tried to downgrade/update woocommerce didn't work..

```
2020-09-04T23:08:40+00:00 CRITICAL Uncaught RuntimeException: Error saving action: Unable to save action. in /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:33
Stack trace:
#0 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(109): ActionScheduler_wpPostStore->save_action()
woocommerce/woocommerce#1 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(59): ActionScheduler_ActionFactory->store()
woocommerce/woocommerce#2 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/functions.php(18): ActionScheduler_ActionFactory->single()
woocommerce/woocommerce#3 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/queue/class-wc-action-queue.php(44): as_schedule_single_action()
woocommerce/woocommerce#4 /var/www/vhosts/jopa in /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 33
```

**Comment by rrennick** [comment] 2020-09-15 17:48
Closing as a duplicate of #587

**Closed by rrennick** 2020-09-15 17:48 UTC
