### ISSUE TITLE
Re-visiting validity of table names

### ISSUE THREAD

**Issue by bor0** [woocommerce/action-scheduler#516] opened 2020-04-06 15:01 UTC
We are seeing some issues with Action Scheduler and Bookings. It happens in an instance with WP Rocket. This likely caused the Bookings issue which flooded our Google API quota, disabling Bookings Google integration for all users.

Customers get this error:

```
[06-Apr-2020 13:41:24 UTC] WordPress database error Table 'matttho9_dev.a' doesn't exist for query SELECT a.action_id FROM  a WHERE a.hook='wc-booking-poll-google-cal' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Bookings_Google_Calendar_Connection->maybe_schedule_poller, as_next_scheduled_action, ActionScheduler_DBStore->find_action
```

Since `find_actions` fail, Bookings schedules thousands of polling events.

From here, it looks like the `$wpdb-><table_name>` is not initialized in some cases. The fix in #498 fixed this for `save_action`, however, we are seeing issues with `find_action` now.

WC Version: 4.0.1
REST API Version: :heavy_check_mark: 1.0.7
WC Blocks Version: :heavy_check_mark: 2.5.14
Action Scheduler Version: :heavy_check_mark: 3.1.4
WC Admin Version: :heavy_check_mark: 1.0.3

Related threads: [#](https://a8c.slack.com/archives/C0E1AV8T0/p1586183999437100), [#](https://a8c.slack.com/archives/C0D9EC4H0/p1586177361091700)

**Comment by crstauf** [comment] 2020-04-06 21:37
I had this error recently as well: turned out I was attempting to interact with AS prior to `init:1` action.

@bor0 I expect you and the devs at Automattic have checked that already, so more likely a helpful note for anyone else that arrives here.

**Comment by bor0** [comment] 2020-04-06 21:58
We were using it on `shutdown:10`, however, `shutdown:1` seems to fix the issue. Will post details as soon as we have them.

**Comment by thenbrent** [comment] 2020-04-07 04:29
> We were using it on `shutdown:10`, however, `shutdown:1` seems to fix the issue. 

That makes me wonder if this is related to the Async runner somehow too, as `ActionScheduler_QueueRunner::maybe_dispatch_async_request()` is attached to `shutdown:10` too.

**Comment by bor0** [comment] 2020-04-07 11:09
Just confirmed today with @jessepearson, `shutdown:1` does *not* fix the issue.

**Comment by rrennick** [comment] 2020-04-07 12:33
> That makes me wonder if this is related to the Async runner somehow too

After looking at the shutdown hook it looks like WP Rocket may be registering its own PHP shutdown hook that's running before WP `shutdown`.

**Comment by jessepearson** [comment] 2020-04-08 17:38
I was able to figure out how to consistently replicate the issue between WP Rocket and Action Scheduler...and Bookings. 

1. WP Rocket settings: [wp-rocket-settings-2020-04-08-5e8e06fa4ac11.json.zip](https://github.com/woocommerce/action-scheduler/files/4451866/wp-rocket-settings-2020-04-08-5e8e06fa4ac11.json.zip)
1. You need to have Bookings installed and connected to a Google calendar. 
1. Create a product if you don't already have one. 
1. Open that product in an incognito/private browsing window. 

This results in this:

> [08-Apr-2020 17:35:27 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /Users/j/sites/clean/wp-includes/wp-db.php on line 647
> [08-Apr-2020 17:35:27 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_groups in /Users/j/sites/clean/wp-includes/wp-db.php on line 647

Which then cascades into multiple db/mysql errors.

**Comment by rrennick** [comment] 2020-04-08 17:43
> WP Rocket settings

@jessepearson Were there settings where the errors didn't occur?

**Comment by jessepearson** [comment] 2020-04-08 17:54
@rrennick I haven't tried anything else at the moment. @bor0 created a patch he had me test out and it stopped the errors from happening, though. I think he may be working on it now.

**Comment by rrennick** [comment] 2020-04-08 18:16
@jessepearson Thanks. We had this issue with WP Rocket and the AS migration in WC 4.0.0. 

Briefly, the issue is that in WP and plugins that use custom tables, variables are created for DB table names to account for the table prefix varying among installs

- `$wpdb->posts` => 'wp_posts'
- `$wpdb->postmeta` => 'wp_postmeta'
- `$wpdb->woocommerce_order_items` => 'wp_woocommerce_order_items'
- `$wpdb->actionscheduler_actions` => 'wp_actionscheduler_actions'

If WP Rocket is active, then in the `shutdown` hook `$wpdb->actionscheduler_actions` is undefined and the AS datastore is effectively unusable.

So the larger issue for the Woo engineering team is what is the best approach to address this across all of our data stores as it could turn into a whack-a-mole scenario.

**Comment by rrennick** [comment] 2020-04-08 18:36
@thenbrent Can you provide your thoughts on whether we should go the route of eliminating the use of `$wpdb->table_names` ?

**Comment by thenbrent** [comment] 2020-04-09 01:19
> If WP Rocket is active, then in the shutdown hook `$wpdb->actionscheduler_actions` is undefined and the AS datastore is effectively unusable.

@rrennick why are those variables undefined with WP Rocket?

**Comment by thenbrent** [comment] 2020-04-09 10:54
Based on #517 and a Slack thread in A8C Slack, there is increasing evidence this issue (or one just like it) doesn't require WP Rocket.

**Comment by rrennick** [comment] 2020-04-09 12:08
> why are those variables undefined with WP Rocket?

I don't have a copy to confirm but it's most likely that WP Rocket destroys its `$wpdb` and creates a default one. Writing the migration action is hooked at priority `0` so either it's done in a negative priority or in its own PHP shutdown hook that is registered before the WP core one.

**Comment by rrennick** [comment] 2020-04-09 13:32
> Based on #517 and a Slack thread in A8C Slack, there is increasing evidence this issue

Both reports in #517 are WC Admin historical data imports. The import schedules a single action that schedules batch actions. The batch actions schedule import actions. That could be caused by #489. If not, then it's likely an issue that's interfering with the import.

**Comment by rrennick** [comment] 2020-04-09 16:42
I thought it would be worth testing another custom database class to rule out the possibility of it being an issue with any custom DB class.

I installed and configured https://github.com/rrennick/SharDB then added the following test code

```
add_action( 'shutdown', function() {
global $wpdb;
as_schedule_single_action( time() + HOUR_IN_SECONDS, 'as-db-test' );
$action = as_next_scheduled_action( 'as-db-test' );
error_log( get_class( $wpdb ) . ': ' . $action );
});
```

The debug log contains the following:
```
[09-Apr-2020 16:33:20 UTC] SharDB: 1586453540
[09-Apr-2020 16:33:20 UTC] SharDB: 1586453540
[09-Apr-2020 16:33:51 UTC] SharDB: 1586453540
[09-Apr-2020 16:33:51 UTC] SharDB: 1586453540

mysql> select action_id from wp_actionscheduler_actions where hook = 'as-db-test';
+-----------+
| action_id |
+-----------+
|     31236 |
|     31237 |
|     31238 |
|     31239 |
|     31240 |
|     31241 |
+-----------+
```

**Comment by rrennick** [comment] 2020-04-20 18:23
I installed WP Rocket with the same test code as my previous comment and am not seeing any errors.

```
[20-Apr-2020 18:17:36 UTC] wpdb: 1587409862
[20-Apr-2020 18:17:37 UTC] wpdb: 1587409862
[20-Apr-2020 18:17:54 UTC] wpdb: 1587409862
[20-Apr-2020 18:17:55 UTC] wpdb: 1587409862
[20-Apr-2020 18:18:36 UTC] wpdb: 1587409862
[20-Apr-2020 18:18:36 UTC] wpdb: 1587409862
```

@jessepearson Can you provide a code snippet that reproduces this with just WC & WP Rocket active?

**Comment by jessepearson** [comment] 2020-04-21 10:33
@rrennick This does it on one of my test sites:

```
add_action( 'plugins_loaded', function(){

	// Query all `wc-booking-poll-google-cal` scheduled actions. 
	$actions = as_get_scheduled_actions(
		array(
			'hook'   => 'wc-booking-poll-google-cal',
		)
	);
});
```

**Comment by rrennick** [comment] 2020-04-21 13:52
> This does it on one of my test sites:

@jessepearson The earliest hook you can use `as_*` functions is `init` per https://actionscheduler.org/api/ - API Function Availability.

**Comment by jessepearson** [comment] 2020-04-21 14:15
@rrennick Ah, gotcha. 

This snippet will produce the error:

```
add_action( 'shutdown', function(){
	$actions = as_get_scheduled_actions( array() );
});
```

Once an existing post/product/page is opened in an incognito window, that's when the notice and error are logged. 

> [21-Apr-2020 14:13:16 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /wp-includes/wp-db.php on line 647
> [21-Apr-2020 14:13:16 UTC] WordPress database error Table 'clean.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions

**Comment by rrennick** [comment] 2020-04-21 16:47
> This snippet will produce the error:

@jessepearson That doesn't produce the error for me. I have WP 5.4 and tried WC 4.0.1, WC master, AS master with shop home page, single product page, product category archive, with or without WP Rocket active on both a logged in window and incognito. I also tried adding to cart to check if it might be triggered by an ajax request.

**Comment by jessepearson** [comment] 2020-04-21 18:38
@rrennick Not sure, then. I have wiped the db of a test site and reinstalled several times now and have been able to replicate it each time. 

1. Activate WC, go through wizard without installing anything additional. 
1. Activate WP Rocket
1. Activate plugin with snippet above as the only thing in it
1. Create product
1. View product in incognito, and it happens on the first to second view

I packed up the site via Duplicator and uploaded it here: https://d.pr/f/3H85Be . Maybe I am missing something that I am doing differently. If that site is used, every time the product is viewed in incognito it creates a new logged error in debug.log.

**Comment by bor0** [comment] 2020-04-24 12:43
I was easily able to reproduce this using only bash:

```
$ wp core download
Downloading WordPress 5.4 (en_US)...
Using cached file '/Users/boro/.wp-cli/cache/core/wordpress-5.4-en_US.tar.gz'...
$ mysql -u root -p -e "CREATE DATABASE test;"
Enter password: 
$ wp config create --dbname=test --dbuser=root
Success: Generated 'wp-config.php' file.
$ wp core install --url="http://localhost:8080" --title="Test" --admin_user=test --admin_email=test@test.com
Admin password: t83#KEOTC5n0t@M1Gr
Success: WordPress installed successfully.
$ wp plugin install woocommerce
Installing WooCommerce (4.0.1)
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.4.0.1.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
$ wp plugin activate woocommerce
Plugin 'woocommerce' activated.
Success: Activated 1 of 1 plugins.
$ mkdir wp-content/mu-plugins
$ cat << EOF > ./wp-content/mu-plugins/test.php
<?php
add_action( 'plugins_loaded', function(){
\$actions = as_get_scheduled_actions(
array(
'hook'   => 'wc-booking-poll-google-cal',
)
);
});
EOF
$ unzip /Users/boro/Downloads/wp-rocket.zip -d ./wp-content/plugins/
$ wp plugin activate wp-rocket
WordPress database error Table 'test.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 AND a.hook='wc-booking-poll-google-cal' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by include('phar:///Users/boro/bin/wp/php/boot-phar.php'), include('phar:///Users/boro/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WP_CLI\Runner->{closure}, as_get_scheduled_actions, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
Plugin 'wp-rocket' activated.
Success: Activated 1 of 1 plugins.
$ wp plugin activate wp-rocket
WordPress database error Table 'test.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 AND a.hook='wc-booking-poll-google-cal' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by include('phar:///Users/boro/bin/wp/php/boot-phar.php'), include('phar:///Users/boro/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WP_CLI\Runner->{closure}, as_get_scheduled_actions, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
Warning: Plugin 'wp-rocket' is already active.
Success: Plugin already activated.
```

**Comment by rrennick** [comment] 2020-04-24 12:47
@bor0 Explained here https://github.com/woocommerce/action-scheduler/issues/516#issuecomment-617194257. Action Scheduler still supports the CPT data store. CPTs cannot be registered before `init`.

**Comment by bor0** [comment] 2020-04-24 12:53
I was able to reproduce it again, using `shutdown` instead of `plugins_loaded` and following @bubbles steps:

1. Ran WC setup wizard
2. Create a product with price 15
3. Save product
4. View from incognito

Apache error logs:

```
[Fri Apr 24 14:52:56.619229 2020] [php7:notice] [pid 17364] [client ::1:65285] WordPress database error Table 'test.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 AND a.hook='wc-booking-poll-google-cal' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions, referer: http://localhost:8080/test/?product=asdf
```

**Comment by rrennick** [comment] 2020-04-24 12:57
@bor0 Can you post your local setup?

**Comment by bor0** [comment] 2020-04-24 12:59
You mean a zip of the instance or system logs?

**Comment by rrennick** [comment] 2020-04-24 13:01
Configuration. I've not been able to do any investigation because I've not been able to reproduce in my dev environment.

**Comment by bor0** [comment] 2020-04-24 13:11
@rrennick you should be able to reproduce using the bash commands I gave. I don't know what parts of my configuration you may be interested, `wp-config.php`, or something else? I am using a Mac, manually installed Apache/PHP/MySQL with brew. No virtual machines or anything.

Here are the commands I used:
```
$ wp core download
$ mysql -u root -p -e "CREATE DATABASE test;"
$ wp config create --dbname=test --dbuser=root
$ wp core install --url="http://localhost:8080/test/" --title="Test" --admin_user=test --admin_email=test@test.com
$ wp plugin install woocommerce
$ wp plugin activate woocommerce
$ mkdir wp-content/mu-plugins
$ cat << EOF > ./wp-content/mu-plugins/test.php
<?php
add_action( 'shutdown', function(){
\$actions = as_get_scheduled_actions(
array(
'hook'   => 'wc-booking-poll-google-cal',
)
);
});
EOF
$ unzip /Users/boro/Downloads/wp-rocket.zip -d ./wp-content/plugins/
$ wp plugin activate wp-rocket
$ wp shell
wp> $x = new WC_Product();
wp> $x->set_name( 'Test' );
wp> $x->set_price( 15 );
wp> $x->save()
wp> 
```

Next, visit http://localhost:8080/test/wp-admin/admin.php?page=wc-setup using all defaults. After done setting up, visit http://localhost:8080/test/?product=test in Incognito mode and see this in the Apache logs:

```
[Fri Apr 24 15:10:09.939393 2020] [php7:notice] [pid 17362] [client ::1:49324] WordPress database error Table 'test.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 AND a.hook='wc-booking-poll-google-cal' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions, referer: http://localhost:8080/test/?product=asdf
```

**Comment by rrennick** [comment] 2020-04-27 16:42
@jessepearson Thanks for all your help on testing & reproducing the issue.

@bor0 I've created #536 to address the underlying issue. After browsing through the folder structure of WP Rocket it seems most likely that one of the libraries it uses suppresses the logging of an error (leaving just the message from the AS function call in `shutdown`). Here's my error log from looking at a PR that pulled in the wrong WC Admin package:

```
[27-Apr-2020 13:14:42 UTC] PHP Fatal error:  require_once(): Failed opening required '/Users/ronrennick/Sites/ron/wp-content/plugins/woocommerce/packages/woocommerce-admin//includes/feature-config.php' (include_path='.:/usr/local/Cellar/php/7.4.5_2/share/php/pear') in /Users/ronrennick/Sites/ron/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/FeaturePlugin.php on line 70
[27-Apr-2020 13:14:42 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /Users/ronrennick/Sites/ron/wp-includes/wp-db.php on line 647
[27-Apr-2020 13:14:42 UTC] WordPress database error Table 'ron.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions
```

The AS documentation will be updated to reflect that AS function should not be used in `shutdown` and I'll add a `shutdown` deprecated notice to all of the functions. I'll close this issue.

**Closed by rrennick** 2020-04-27 16:42 UTC
Labels: status: needs feedback

**Comment by bor0** [comment] 2020-04-27 16:49
Thanks for the investigation @rrennick! Sounds good.
