### ISSUE TITLE
Tables do not write

### ISSUE THREAD

**Issue by wpinventory** [woocommerce/action-scheduler#603] opened 2020-08-18 18:41 UTC
After activating this plugin per the documentation here:

https://wpmailsmtp.com/docs/how-to-troubleshoot-action-scheduler-issues-wp-mail-smtp-2-1-1/

I get the following Fatal error because it will not create the table if it does not exist.

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table 'resta064_sg.wp_j4m14t1mrm_actionscheduler_actions' doesn't exist in /home/resta064/public_html/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /home/resta064/public_html/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /home/resta064/public_html/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /home/resta064/public_html/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 /home/resta064/public_html/wp-content/pl in /home/resta064/public_html/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

**Comment by rrennick** [comment] 2020-08-18 18:42
Try installing Action Scheduler directly through the plugin installer to see if it creates the tables.

**Comment by wpinventory** [comment] 2020-08-18 18:50
I uploaded the ZIP I download via the Plugins page "Add New" and uploaded.
Any ideas?

**Comment by rrennick** [comment] 2020-08-18 18:52
> Any ideas?

Can you get the error message from your server logs indicating why the tables aren't created?

**Comment by wpinventory** [comment] 2020-08-18 19:00
Attached is the php error log.  Rather long, but scroll all the way to the bottom please.

https://www.dropbox.com/s/j8g8izza5kzabti/php_errorlog?dl=0

**Comment by rrennick** [comment] 2020-08-18 19:09
@Ceaco That doesn't have the error message for creating the table.

Please try the instructions in #587 (comment). Replace the `wp_` in the table name with `wp_j4m14t1mrm_`.

**Comment by wpinventory** [comment] 2020-08-18 19:26
@rrennick 

That is what I was going to do next.  Just run the script from the MySQL side.  I guess that will have to do.  Thanks for your help.

**Comment by danieliser** [comment] 2020-08-18 19:43
@wpinventory @rrennick - See my most recent comment on #587.

I'm starting to wonder if this table isn't actually erroring during install, but rather failing to ever get processed in the first place and marked as installed.

Is there potential that this query doesn't ever get run but the others do? If the one just before it failed after sending query to MySQL it could cause that no?

**Comment by danieliser** [comment] 2020-08-18 19:49
@wpinventory - From your logs you have quite a few issues you need to check into. Lots of table doesn't exist errors in there, even for wp_options core tables, so that is a bigger concern than this plugin.

Also saw errors indicating your DB is dropping or overloaded from time to time.

Lots of errors from a couple specific plugins that could be at play as well.

Might be worth trying to clean up all those other issues to see if they were part of the issue as well.

**Comment by rrennick** [comment] 2020-08-18 19:56
> Is there potential that this query doesn't ever get run but the others do?

No. It's the first table created.

**Comment by wpinventory** [comment] 2020-08-18 20:16
@danieliser @rrennick 

Thanks for both of your help.  I am working on the logs and DB errors as we speak.  However, I do see the options table (in cPanel right now).  I'm going to strip the file contents and re-upload and get fresh data and work back from there.

**Comment by rrennick** [comment] 2020-09-15 17:49
Closing as a duplicate of #587

**Closed by rrennick** 2020-09-15 17:49 UTC
