### ISSUE TITLE
Whole site returning 500 error after activating plugin

### ISSUE THREAD

**Issue by carlomanf** [woocommerce/action-scheduler#799] opened 2022-02-03 07:17 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After trying to activate the plugin, the server is timing out and returning a 500 error. This didn't happen before today, but I can't be certain what caused it to start happening. It happens even with no other plugins active.

I am seeing the following in the php error log:

```
[03-Feb-2022 04:30:38 UTC] WordPress database error Commands out of sync; you can't run this command now for query UPDATE `wp_8_options` SET `option_value` = '1643862698' WHERE `option_name` = 'action_scheduler_lock_async-request-runner' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_OptionLock->set, update_option, QM_DB->query
[03-Feb-2022 04:30:38 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT COUNT(DISTINCT claim_id) FROM wp_8_actionscheduler_actions WHERE claim_id != 0 AND status IN ('pending', 'in-progress') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_DBStore->get_claim_count, QM_DB->query
[03-Feb-2022 04:30:38 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT a.action_id FROM wp_8_actionscheduler_actions a WHERE 1 = 1 AND a.status IN ('pending') AND a.scheduled_date_gmt <= '2022-02-03 04:30:38' LIMIT 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_DBStore->query_actions, QM_DB->query
[03-Feb-2022 04:32:45 UTC] WordPress database error Commands out of sync; you can't run this command now for query UPDATE `wp_8_options` SET `option_value` = '1643862825' WHERE `option_name` = 'action_scheduler_lock_async-request-runner' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_OptionLock->set, update_option, QM_DB->query
[03-Feb-2022 04:32:45 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT COUNT(DISTINCT claim_id) FROM wp_8_actionscheduler_actions WHERE claim_id != 0 AND status IN ( 'pending', 'in-progress') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_DBStore->get_claim_count, QM_DB->query
[03-Feb-2022 04:32:45 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT a.action_id FROM wp_8_actionscheduler_actions a WHERE 1=1 AND a.status IN ('pending') AND a.scheduled_date_gmt <= '2022-02-03 04:32:45' LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_DBStore->query_actions, QM_DB->query
[03-Feb-2022 04:34:42 UTC] WordPress database error Commands out of sync; you can't run this command now for query UPDATE `wp_8_options` SET `option_value` = '1643862942' WHERE `option_name` = 'action_scheduler_lock_async-request-runner' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_OptionLock->set, update_option, QM_DB->query
[03-Feb-2022 04:34:42 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT COUNT(DISTINCT claim_id) FROM wp_8_actionscheduler_actions WHERE claim_id != 0 AND status IN ( 'pending', 'in-progress') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_DBStore->get_claim_count, QM_DB->query
[03-Feb-2022 04:34:42 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT a.action_id FROM wp_8_actionscheduler_actions a WHERE 1=1 AND a.status IN ('pending') AND a.scheduled_date_gmt <= '2022-02-03 04:34:42' LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_DBStore->query_actions, QM_DB->query
```

### Expected behavior

The plugin should activate normally.

### Actual behavior

The plugin does activate, but the whole site becomes inaccessible.

Interestingly, when activating on the network, the plugin works fine on every site except site number 8, as you can see in the error log.

This leads me to guess that another plugin may have corrupted some data in the tables for site number 8. Even so, it is the responsibility of this plugin to be able to handle its own data, even if it may be corrupted.

### Steps to reproduce

1. Attempt to activate woocommerce (site-activating for number 8 and network-activating both yielded same result)

### WordPress Environment

`
### WordPress Environment ###

WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.9.1-alpha-52643
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.33
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Action Scheduler ###

Complete: 14
Oldest: 2022-01-30 05:07:49 +0000
Newest: 2022-01-31 00:00:56 +0000

### Status report information ###

Generated at: 2022-02-03 06:52:19 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment] 2022-02-11 17:49
The queries seem related to Action Scheduler but the error suggests to me that another plugin is the cause of this problem, perhaps because a stored procedure is being called [but things are not cleaned up afterwards](https://www.php.net/manual/en/mysqli.query.php#102904).

The system information you shared seems incomplete/does not include details of the other plugins you are using, but since it sounds like one site in particular is impacted perhaps you could look at that and see if there are plugins activated only on that site which you could try disabling?

**Comment by carlomanf** [comment] 2022-02-11 22:41
As indicated in the original report, the errors continued happening when woocommerce was the only plugin active.

**Comment by carlomanf** [comment] 2022-02-11 23:10
Do you believe it's possible for a plugin to cause this even after being deactivated? I'm not aware of any plugins that are using those particular php functions. I can also confirm that the site normally has no plugins active of its own other than the network-active ones.

**Comment by barryhughes** [comment] 2022-02-14 16:35
> As indicated in the original report, the errors continued happening when woocommerce was the only plugin active.

OK, but I wanted to clarify especially since we're dealing with a multisite network.

For instance, even if WooCommerce is the only plugin activated within that one site, you may have other [network-activated plugins](https://wordpress.org/support/article/multisite-network-administration/#plugins) and/or you may have [must-use or drop-in plugins](https://hakre.wordpress.com/2010/05/01/must-use-and-drop-ins-plugins/) running. Any of those could introduce this problem. Theoretically, even your theme could be a factor.

> Do you believe it's possible for a plugin to cause this even after being deactivated?

A plugin could definitely add a new stored procedure to the database which would then persist after the plugin has been deactivated—but in this case I don't think that would, by itself, cause the problem: if this is indeed the source of the error, code somewhere would need to actually *call* that stored procedure but fail to fetch all of the results.

[Action Scheduler](https://actionscheduler.org/) (this issue was transferred here, though you originally reported it in the WooCommerce issue tracker) does not use stored procedures, nor does the current/stable version of WooCommerce. That is why I was looking to other components as the possible source of this problem.

**Comment by carlomanf** [comment] 2022-02-14 22:23
> For instance, even if WooCommerce is the only plugin activated within that one site, you may have other [network-activated plugins](https://wordpress.org/support/article/multisite-network-administration/#plugins) and/or you may have [must-use or drop-in plugins](https://hakre.wordpress.com/2010/05/01/must-use-and-drop-ins-plugins/) running. Any of those could introduce this problem. Theoretically, even your theme could be a factor.

To clarify, when I deactivated all plugins, I definitely deactivated the network-active ones as well.

I can confirm there is a `sunrise.php` and one other must-use plugin. I don't remember whether I deactivated these when testing, but they are very simple ones that just modify a few core filters and they certainly don't have anything like the php functions you linked to.

> [Action Scheduler](https://actionscheduler.org/) (this issue was transferred here, though you originally reported it in the WooCommerce issue tracker) does not use stored procedures, nor does the current/stable version of WooCommerce.

Do you know if core has any use of stored procedures?

**Comment by barryhughes** [comment] 2022-02-15 15:25
I don't believe WordPress core uses stored procedures. Could you try running:

```sql
-- List stored procedures
SHOW PROCEDURE STATUS;
```

Depending on how many results, you may wish to filter out some standard procedures with a slightly longer query along these lines:

```sql
SHOW PROCEDURE STATUS 
WHERE (
    `Definer` NOT LIKE 'mysql%'
    AND `Name` NOT LIKE 'ps%'
);
```

Assuming we're on the right track, perhaps the name of one of the procedures will provide a clue as to where it came from (for instance, a future version of WooCommerce *will* introduce a stored procedure, and it will use the `wc_` prefix in its name).

This isn't bullet-proof, as if a stored procedure is involved in this issue it could also conceivably be temporary in nature, but it might get us closer to an answer.

**Comment by carlomanf** [comment] 2022-02-16 00:32
Both queries returned zero results, with the plugin active and with the plugin inactive.

**Comment by barryhughes** [comment] 2022-02-25 21:56
Circling back, I have not found the conditions needed to replicate this (added to which, we haven't received additional reports from others).

Unless this can be distilled down to a set of steps-to-replicate, I think we'll need to do some more digging. To that end, if you can, it may be worth [enabling the general query log for `mysqld`](https://dev.mysql.com/doc/refman/8.0/en/query-log.html) (or MariaDB equivalent) and seeing if you can identify the queries that occur right before this problem.

**Comment by carlomanf** [comment] 2022-03-18 02:36
If it helps to diagnose, I have several times been able to re-activate the woocommerce plugin with no issues after waiting several days. However, every time, the problem has returned again after a while, forcing me to deactivate it again. I am guessing that the problem resolves itself because some scheduled action expires, but still have not found what it is that brings it back again. I will look into enabling the general query log.

**Comment by barryhughes** [comment] 2022-04-18 23:59
Let us know if there is any more information that might help with this, otherwise we will probably close in due course.

**Comment by carlomanf** [comment] 2022-04-22 04:37
I am currently keeping the plugin deactivated due to this issue, and I have not yet found the time to enable the general query log due to other priorities. If the issue is closed, would I be able to re-open it later with more information?

**Comment by barryhughes** [comment] 2022-04-22 21:50
Creating a new issue with fresh information, linking back to this one for context is probably best. We can keep it open a little longer, though, as you intend to cycle back to it :+1:

**Closed** 2022-05-26 20:44 UTC
Labels: needs feedback, type: support request
