### ISSUE TITLE
 Serious problem with Woocomerce activation with Actionscheduler.

### ISSUE THREAD

**Issue by Alberavid** [woocommerce/action-scheduler#598] opened 2020-08-04 08:24 UTC
Hello I ask them for urgent help, have a problem when I activate Woocomerce, automatically it gives me the error that I show them in Wordpress and have to go away like Wordpress recovery.

I have tried to install Actionscheduler plugin that exists in Github and gives me the same error. 

I have deactivated all the plugins and have erased WP Optimize, pro if he was the causer.

Please can they help me?

Les estoy muy agradecido

This is the error:

Se ha producido un error del tipo E_ERROR en la línea 44 del archivo /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php. Mensaje de error: Uncaught RuntimeException: Error saving action: Error saving action: Table 'BBDD_Artresponsive.FRJFDft5_actionscheduler_actions' doesn't exist in /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 
Stack trace: 
#0 /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plugins/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action() 
#1 /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action() 
#2 /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store() 
#3 /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plugins/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single() 
#4 /var/www/vhosts/artresponsive.com/httpdocs/wp-content/plu

**Comment by rrennick** [comment] 2020-08-04 12:40
@Alberavid Please try the instructions in https://github.com/woocommerce/action-scheduler/issues/587#issuecomment-658168773. Replace the `wp_` in the table name with `FRJFDft5_`.

**Comment by rrennick** [comment] 2020-08-18 19:10
Closing as duplicate of #587.

**Closed by rrennick** 2020-08-18 19:10 UTC
Labels: status: needs feedback
