### ISSUE TITLE
Table 'sitename.a' doesn't exist

### ISSUE THREAD

**Issue by Updula** [woocommerce/action-scheduler#542] opened 2020-05-03 20:29 UTC
Hi there, I have installed latest master 3.1.5 but this is still happening

`2020/05/03 20:19:18 [error] 83354#83354: *593656 FastCGI sent in stderr: "PHP message: Error Table 'sitename.a' doesn't exist SELECT a.action_id FROM a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 القادم من shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_actionPHP message: Error Table 'sitename.a' doesn't exist SELECT a.action_id FROM a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 القادم من shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_actionPHP message: Error Table 'sitename.a' doesn't exist SELECT a.action_id FROM a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 القادم من shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_actionPHP message: Error Table 'sitename.a' doesn't exist SELECT a.action_id FROM a WHERE a.hook='action_scheduler/migration_hook' AND a.stat`

I thought it was related to a conflict with WP Rocket but this doesn't seem to be the cause.

Setup is latest WC 4.0.1 and AS 3.1.5 on Kinsta hosting

**Comment by rrennick** [comment] 2020-05-04 14:23
> `shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters,`

Version 3.1.5 doesn't use the `shutdown` hook. Can you check your WC System Status Report to see which version is in use?

**Comment by Updula** [comment] 2020-05-04 17:14
@rrennick It says 3.1.4 but I uploaded the 3.1.5 release. Seems that the release it still using old version number so it's a bit confusing.

So far I didn't face the issue again - will update in next 24 hrs.

**Comment by rrennick** [comment] 2020-05-11 13:16
@Updula Closing this assuming the issue is resolved. If not, please let us know.

**Closed by rrennick** 2020-05-11 13:16 UTC
Labels: question
