### ISSUE TITLE
Duplicate jobs result in action scheduler "pending" section

### ISSUE THREAD

**Issue by rafdizzle86** [woocommerce/action-scheduler#386] opened 2019-11-04 04:39 UTC
I've been using the plugin to schedule jobs in the following way:

```
static function schedule_my_job() {
    $pending_my_job = as_get_scheduled_actions(
        array(
            'hook' => 'my_job',
            'status' => ActionScheduler_Store::STATUS_PENDING
        )
    );

    if ( empty( $pending_my_job ) ) {
        as_schedule_recurring_action( strtotime( '+5 second' ), 5, 'my_job' );
    }
}
```

However in the "pending" section the "my_job" job keeps showing up twice - am I scheduling it incorrectly?

**Comment by thenbrent** [comment] 2019-11-04 05:39
Instead of `as_get_scheduled_actions()`, you could just use `as_next_scheduled_action( 'my_job' )`. I'm not sure that is the issue though.

How are you calling `schedule_my_job()`? i.e. is it attached to `admin_init` or similar

There could be a bug here so I'd like to reproduce.

**Comment by thenbrent** [comment] 2019-11-06 00:45
@rafdizzle86 could you share how you're calling `schedule_my_job()`? I have a theory on this now, that it may be caused by using `init` to schedule the job.

**Comment by rafdizzle86** [comment] 2019-11-06 09:47
@thenbrent this is how I have it set up:

```
class WCLSI_Item_Poller {
    public static function init() {
        add_action( 'init', array( get_called_class(), 'schedule_wclsi_poller' ), 10, null, null );
        add_action( 'wclsi_poll', array( get_called_class(), 'poll'), 10 );
    }

    static function schedule_wclsi_poller() {
        $pending_wclsi_poller = as_get_scheduled_actions(
            array(
                'hook' => 'wclsi_poll',
                'status' => ActionScheduler_Store::STATUS_PENDING
            )
        );

        if ( empty( $pending_wclsi_poller ) ) {
            as_schedule_recurring_action( strtotime( '+5 second' ), 5, 'wclsi_poll' );
        }
    }
}

WCLSI_Item_Poller::init();

**Comment by thenbrent** [comment] 2019-11-07 00:26
Thanks @rafdizzle86. Can you please also confirm the version you are using? Is it 2.2.5 or a 3.0 version?

If you're using 2.n, this is likely the same issue as https://github.com/woocommerce/action-scheduler/issues/291.

That has been properly address with 3.0 so you can use the 3.0.0-RC-3 version instead.

**Comment by thenbrent** [comment] 2019-11-12 03:08
Based on #387, this is currently an issue with 3.0 also.

**Comment by rrennick** [comment] 2019-11-12 12:33
I added the above code to my install and do not get duplicate actions. I updated it to the following and deleted the pending action in the dashboard. No duplicate actions this way either.

```
class WCLSI_Item_Poller {
    public static function init() {
        add_action( 'init', array( get_called_class(), 'schedule_wclsi_poller' ), 10, null, null );
        add_action( 'wclsi_poll', array( get_called_class(), 'poll'), 10 );
    }

    static function schedule_wclsi_poller() {
        $pending_wclsi_poller = as_next_scheduled_action( 'wclsi_poll' );

        if ( empty( $pending_wclsi_poller ) ) {
            as_schedule_recurring_action( strtotime( '+5 second' ), 5, 'wclsi_poll' );
        }
    }
}

WCLSI_Item_Poller::init();
```

**Comment by krazik** [comment] 2019-11-12 16:16
I am also getting duplicate schedule actions.  I have isolated my problem to this line of code https://github.com/woocommerce/action-scheduler/blob/52bd35581c73c77094b0b2dd4b639e595a009457/functions.php#L140

my action takes about 30 seconds to run, during that time there are no actions with `pending` status.  Just one in process and a bunch of complete, so this causes `as_next_scheduled_action` to return false then the you create a 2nd (or over time a 3rd or 4th copy). 

Seems you should also check for running process here.

**Comment by rafdizzle86** [comment] 2019-11-12 16:23
@thenbrent I'm using whatever comes packaged with WooCommerce which I think is 3.0

**Comment by thenbrent** [comment] 2019-11-13 04:25
I've submitted a fix for this in https://github.com/woocommerce/action-scheduler/pull/392

**Closed** 2019-11-14 00:55 UTC
